### ISSUE TITLE
Open to adding a command line version?

### ISSUE THREAD

**Issue by chmac** [Pieohpah/gps-file-converter#1]
Firstly, thanks for publishing this. I found it via yarn package search, and it seems like exactly what I want. A simple utility to ingest a track as a GPX and output KML, or vice versa.

Would you be open to adding a command line script? I could submit a PR if you are. Otherwise if that doesn't seem fitting, I can also import your package and then build a simple CLI interface separately. Figured I'd reach out before starting work on a PR.

**Comment by chmac** [comment]
I also just found https://github.com/romasan/gpx2kml which seems like it does something similar, although it doesn't support GeoJSON.

**Comment by Pieohpah** [comment]
Hi CallumThanks for asking. Feel free to implement however you like. I might not have included the licencing, but it’s MIT. So by all means, use it. I’m not currently activly updating it. It works for what it’s built for but lacking in KML coverage.Best regards/Peter22 apr. 2023 kl. 09:40 skrev Callum Macdonald ***@***.***>:﻿
I also just found https://github.com/romasan/gpx2kml which seems like it does something similar, although it doesn't support GeoJSON.

**Comment by chmac** [comment]
Gotcha. Thanks for the quick reply.

I tried out the gpx2kml script and it seems to work as advertised, and already has a command line util, so I'll close this issue for now, but circle back to it if something changes.

Thanks for making open source software. 🧡

**Comment by Pieohpah** [comment]
You’re welcome.Glad that it could be of use to somebody more than me 😁27 apr. 2023 kl. 21:13 skrev Callum Macdonald ***@***.***>:﻿
Closed #1 as completed.
